### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Unsupported numpy type: NPY_INT

### ISSUE THREAD

**Issue by Michdo93** [jackokaiser/ros_tensorflow_tutorial#1]
rosrun ros_tensorflow node.py

[INFO] [1594901673.763953]: Creating the Tensorflow model
WARNING:tensorflow:From /home/pi/catkin_ws/src/ros_tensorflow/src/ros_tensorflow/model.py:20: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

[INFO] [1594901674.086283]: ros_tensorflow node initialized
[INFO] [1594901674.101339]: Prediction from loop:
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/ros_tensorflow/nodes/node.py", line 94, in <module>
    main()
  File "/home/pi/catkin_ws/src/ros_tensorflow/nodes/node.py", line 87, in main
    y, confidence = ri.wrapped_model.predict(x.reshape(1, -1))
  File "/home/pi/catkin_ws/src/ros_tensorflow/src/ros_tensorflow/model.py", line 31, in predict
    out = self.model.predict(x)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 722, in predict
    callbacks=callbacks)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 393, in model_iteration
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/backend.py", line 3580, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: Unsupported numpy type: NPY_INT

**Comment by Titook** [comment]
我也有这个问题

**Comment by Titook** [comment]
主要是找不到它哪里的输入时numpy，我检查了输入都改为tensor了呀
